# Cyclistic Bike-Share Data Preparation & Ingestion

## Objective
This notebook initiates the Cyclistic Bike-Share Analytics project by performing the critical steps of raw data ingestion and initial preparation. Key objectives include:
-   **Efficient Data Loading**: Consolidate 12 months of historical trip data from individual CSV files into a single, unified Pandas DataFrame.
-   **Schema & Type Enforcement**: Validate and convert data types for critical columns (e.g., `started_at`, `ended_at` to datetime, categorical features) to ensure data quality and optimize memory usage.
-   **Initial Data Quality Filtering**: Apply preliminary filters to address any immediate data inconsistencies or invalid records at the ingestion stage, ensuring a clean foundation for subsequent analysis.

## Data Lineage & Security
Maintaining data integrity, traceability, and adherence to data warehousing principles is paramount. This notebook implements the following:
-   **Zero Column Loss Principle**: All original columns from the raw source files are preserved during the initial loading phase. No data is prematurely dropped or aggregated, ensuring full fidelity to the source.
-   **Immutable Source Reference**: The raw CSV files are treated as the definitive, immutable source. This notebook reads data without modifying the original files.
-   **Traceability Mechanism**: A `source_file` column is temporarily introduced during the concatenation process to explicitly track the origin of each record. This facilitates auditing and debugging, and is subsequently removed once its lineage purpose is served.
-   **Optimized Persistence**: The prepared dataset is saved in an optimized format (e.g., Parquet) for efficient storage and high-performance access in downstream analytical processes.

The dataset consists of Cyclistic’s historical trip data for the last 12 months, stored as 12 CSV files, one for each month. The data has been made available by Motivate International Inc. under this license. Each file contains 13 fields:

- `ride_id`: Unique ID for each ride taken by the customer
- `rideable_type`: Type of bicycle among classic_bike, dock_bike and electric_bike
- `started_at`: Time at which the ride started
- `ended_at`: Time at which the ride ended
- `start_station_name`: Station at which the ride started
- `start_station_id`: The ID of the station at which the ride started
- `end_station_name`: Station at which the ride ended
- `end_station_id`: The ID of the station at which the ride ended
- `start_lat`: The latitude of the station at which the ride started
- `start_lng`: The longitude of the station at which the ride started
- `end_lat`: The latitude of the station at which the ride ended
- `end_lng`: The longitude of the station at which the ride ended
- `member_casual`: Type of user among member or casual

In [1]:
#importing lib's
import os
from datetime import datetime
import numpy as np 
import pandas as pd
import matplotlib as plt
from pathlib import Path

In [2]:
DATA_PATH = Path("D:\cicyle project\Cyclistic-dataset") 
csv_files = sorted(DATA_PATH.glob("*.csv"))

csv_files

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Youssef\AppData\Local\Temp\ipykernel_28820\1107838869.py:1: SyntaxWarning: invalid escape sequence '\c'
  DATA_PATH = Path("D:\cicyle project\Cyclistic-dataset")

[WindowsPath('D:/cicyle project/Cyclistic-dataset/202505-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202506-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202507-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202508-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202509-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202510-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202511-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202512-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202601-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202602-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202603-divvy-tripdata.csv'),
 WindowsPath('D:/cicyle project/Cyclistic-dataset/202604-divvy-tripdata.csv')]

In [3]:
df_list = []

for file in csv_files:
    temp_df = pd.read_csv(file)
    temp_df["source_file"] = file.name
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

In [4]:
df.shape

(5697455, 14)

In [5]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5697455 entries, 0 to 5697454
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  source_file         object
dtypes: float64(4), object(10)
memory usage: 608.6+ MB

In [7]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file
0,BADF67E2C5058F19,classic_bike,2025-05-11 17:22:39.471,2025-05-11 18:11:19.249,DuSable Lake Shore Dr & North Blvd,LF-005,Winthrop Ave & Lawrence Ave,TA1308000021,41.911722,-87.626804,41.968812,-87.657659,member,202505-divvy-tripdata.csv
1,0210AE485D59C8C5,electric_bike,2025-05-05 08:02:09.251,2025-05-05 08:12:07.549,Damen Ave & Grand Ave,TA1308000006,Desplaines St & Jackson Blvd,15539,41.892394,-87.676885,41.878119,-87.643948,member,202505-divvy-tripdata.csv
2,5E68FE5B9283E4C4,classic_bike,2025-05-02 10:32:33.062,2025-05-02 10:39:07.262,LaSalle St & Illinois St,13430,Clark St & Elm St,TA1307000039,41.890762,-87.631697,41.903322,-87.632999,member,202505-divvy-tripdata.csv
3,13D2DCD6FB872858,classic_bike,2025-05-12 11:12:16.579,2025-05-12 11:17:25.126,Milwaukee Ave & Rockwell St,13242,Damen Ave & Cortland St,13133,41.920330,-87.693090,41.915983,-87.677335,member,202505-divvy-tripdata.csv
4,F04DF9EE163351DD,classic_bike,2025-05-01 10:13:36.821,2025-05-01 10:17:40.548,Halsted St & Roosevelt Rd,TA1305000017,Clinton St & Roosevelt Rd,WL-008,41.867324,-87.648625,41.867118,-87.641088,member,202505-divvy-tripdata.csv

In [8]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

In [9]:
categorical_cols = ['rideable_type', 'start_station_name', 'end_station_name', 'member_casual', 'source_file']
for col in categorical_cols:
    df[col] = df[col].astype('category')

In [11]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file
0,BADF67E2C5058F19,classic_bike,2025-05-11 17:22:39.471,2025-05-11 18:11:19.249,DuSable Lake Shore Dr & North Blvd,LF-005,Winthrop Ave & Lawrence Ave,TA1308000021,41.911722,-87.626804,41.968812,-87.657659,member,202505-divvy-tripdata.csv
1,0210AE485D59C8C5,electric_bike,2025-05-05 08:02:09.251,2025-05-05 08:12:07.549,Damen Ave & Grand Ave,TA1308000006,Desplaines St & Jackson Blvd,15539,41.892394,-87.676885,41.878119,-87.643948,member,202505-divvy-tripdata.csv
2,5E68FE5B9283E4C4,classic_bike,2025-05-02 10:32:33.062,2025-05-02 10:39:07.262,LaSalle St & Illinois St,13430,Clark St & Elm St,TA1307000039,41.890762,-87.631697,41.903322,-87.632999,member,202505-divvy-tripdata.csv
3,13D2DCD6FB872858,classic_bike,2025-05-12 11:12:16.579,2025-05-12 11:17:25.126,Milwaukee Ave & Rockwell St,13242,Damen Ave & Cortland St,13133,41.920330,-87.693090,41.915983,-87.677335,member,202505-divvy-tripdata.csv
4,F04DF9EE163351DD,classic_bike,2025-05-01 10:13:36.821,2025-05-01 10:17:40.548,Halsted St & Roosevelt Rd,TA1305000017,Clinton St & Roosevelt Rd,WL-008,41.867324,-87.648625,41.867118,-87.641088,member,202505-divvy-tripdata.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5697450,3EBF5095F5EDD850,electric_bike,2026-04-30 17:28:33.339,2026-04-30 17:33:55.678,Broadway & Ridge Ave,CHI00337,Winchester (Ravenswood) Ave & Balmoral Ave,CHI00630,41.984045,-87.660274,41.979762,-87.677530,member,202604-divvy-tripdata.csv
5697451,9E8DA9D139892463,classic_bike,2026-04-29 18:54:07.910,2026-04-29 19:01:38.331,Broadway & Ridge Ave,CHI00337,Winchester (Ravenswood) Ave & Balmoral Ave,CHI00630,41.984045,-87.660274,41.979762,-87.677530,member,202604-divvy-tripdata.csv
5697452,37C480C304D1D8C1,electric_bike,2026-04-09 15:49:52.265,2026-04-09 16:19:23.924,Wells St & Hubbard St,CHI00332,Francisco Ave & Foster Ave,CHI00638,41.889906,-87.634266,41.975633,-87.701419,member,202604-divvy-tripdata.csv
5697453,27B1BFA25C7449F4,electric_bike,2026-04-21 15:37:19.424,2026-04-21 15:42:02.893,Wells St & Hubbard St,CHI00332,Wells St & Madison St,CHI02102,41.889906,-87.634266,41.881990,-87.634180,casual,202604-divvy-tripdata.csv
5697454,5610B1C41963BAD1,classic_bike,2026-04-14 17:14:32.550,2026-04-14 17:38:55.543,Wells St & Hubbard St,CHI00332,Shedd Aquarium,CHI00533,41.889906,-87.634266,41.867226,-87.615355,member,202604-divvy-tripdata.csv

In [12]:
df = df.drop(columns=['source_file'])

In [13]:
df.to_parquet('date_prepared', index= False)

In [53]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file,day_of_week,month,hour,date,ride_length,ride_length_min
0,BADF67E2C5058F19,classic_bike,2025-05-11 17:22:39.471,2025-05-11 18:11:19.249,DuSable Lake Shore Dr & North Blvd,LF-005,Winthrop Ave & Lawrence Ave,TA1308000021,41.911722,-87.626804,41.968812,-87.657659,member,202505-divvy-tripdata.csv,Sunday,May,17,2025-05-11,48.662967,48.66
1,0210AE485D59C8C5,electric_bike,2025-05-05 08:02:09.251,2025-05-05 08:12:07.549,Damen Ave & Grand Ave,TA1308000006,Desplaines St & Jackson Blvd,15539,41.892394,-87.676885,41.878119,-87.643948,member,202505-divvy-tripdata.csv,Monday,May,8,2025-05-05,9.971633,9.97
2,5E68FE5B9283E4C4,classic_bike,2025-05-02 10:32:33.062,2025-05-02 10:39:07.262,LaSalle St & Illinois St,13430,Clark St & Elm St,TA1307000039,41.890762,-87.631697,41.903322,-87.632999,member,202505-divvy-tripdata.csv,Friday,May,10,2025-05-02,6.570000,6.57
3,13D2DCD6FB872858,classic_bike,2025-05-12 11:12:16.579,2025-05-12 11:17:25.126,Milwaukee Ave & Rockwell St,13242,Damen Ave & Cortland St,13133,41.920330,-87.693090,41.915983,-87.677335,member,202505-divvy-tripdata.csv,Monday,May,11,2025-05-12,5.142450,5.14
4,F04DF9EE163351DD,classic_bike,2025-05-01 10:13:36.821,2025-05-01 10:17:40.548,Halsted St & Roosevelt Rd,TA1305000017,Clinton St & Roosevelt Rd,WL-008,41.867324,-87.648625,41.867118,-87.641088,member,202505-divvy-tripdata.csv,Thursday,May,10,2025-05-01,4.062117,4.06